#ifndef BONDAR_EVENTS
#define BONDAR_EVENTS

#define EVENT_UNDEFINED 0

//SENSOR READINGS 1-15

#define EVENT_READ_GPS 1
#define EVENT_READ_ACCELEROMETER 2
#define EVENT_READ_MAGNETOMETER 3
#define EVENT_READ_GYROSCOPE 4
#define EVENT_READ_BAROMETER 5

//NOTIFICATIONS 16-31

#define EVENT_APOGEE  16
#define EVENT_MAIN_FIRED 17
#define EVENT_DROGUE_FIRED 18

//ERRORS

#define EVENT_ERROR -1


#endif